name: WebDev Journal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format_testing_doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'

    - name: Install dependencies
      run: npm install
      
    - name: Check code style for HTML, CSS, and JS
      run: npx prettier --check "**/*.{html,css,js}" || echo "No HTML, CSS, or JS files to format."

    - name: Run unit tests with Jest
      run: npx jest

    - name: Generate documentation
      run: npx jsdoc -c jsdoc.json
